apiVersion: v1alpha1
kind: Setting
metadata:
  name: halo-theme-vahlok-setting
spec:
  forms:
    - group: basic
      label: 基础
      formSchema:
        - $formkit: text
          name: beian
          label: 备案号
          value: ""
