apiVersion: v1alpha1
kind: Setting
metadata:
  name: halo-theme-vahlok-setting
spec:
  forms:
    - group: basic
      label: 基础
      formSchema:
        - $formkit: text
          name: custom_footer
          label: 页脚文字
          value: "暮灯手札 · 写于人间微暗处"
