apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-vahlok
spec:
  displayName: Vahlok
  author:
    name: Halo Theme Vahlok
  description: 一个以私人随笔和归档阅读为核心的 Halo 主题
  settingName: "halo-theme-vahlok-setting"
  configMapName: "halo-theme-vahlok-configMap"
  version: 1.0.0
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://www.gnu.org/licenses/gpl-3.0.html"
