apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-vahlok
spec:
  displayName: Vahlok
  author:
    name: Azite
    website: https://github.com/Aziteee
  description: Quiet notes from dim light.
  logo: https://s41.ax1x.com/2026/05/29/pmFNE9A.png
  homepage: https://github.com/Aziteee/halo-theme-vahlok#readme
  repo: https://github.com/Aziteee/halo-theme-vahlok
  issues: https://github.com/Aziteee/halo-theme-vahlok/issues
  settingName: "halo-theme-vahlok-setting"
  configMapName: "halo-theme-vahlok-configMap"
  version: 1.0.0
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://www.gnu.org/licenses/gpl-3.0.html"
